# Which company would you choose to work for?
Company A: Strict, serious, and rigorously follows schedules and rules
Company B: Free, undisciplined, doesn't have clear rules or regulations, and everything is talked over and depends on initiative

# What is more difficult for you?
Conscientiously pander to others
Having to say things that you know will hurt the other person

# You have to finish a task to hand in tomorrow that takes 5 hours. At that moment, a friend invites you to play your favorite game. What do you do?
I turn them down and finish the task first
I play first and then finish the task

# Which of these ideas of law are you more inclined to?
The law should be strictly enforced, impartial, and treat everyone equally
The law should be humane and allow for special cases

# What are you normally like in relationships?
Frank, sincere, and I express my thoughts directly
Evasive, thoughtful, and I express my thoughts after deliberation

# When you go to a party, which of these situations describes you best?
I have conversations with everyone
I only talk to people I know well

# When you recall your student life, what do you care about the most?
Grades (admissions to schools, grades achieved, etc.)
Life experiences

# Which of these tasks would you choose from your boss?
Task 1: The process is clear, but the difficulty is beyond your abilities
Task 2: The process of the task is unknown and you need to figure it out while doing it

# Regarding your daily life and social events, you tend to:
Post on social media
Only share with a few friends or family

# When asked for an opinion on something, you normally:
Think and then answer
Answer while thinking

# After completing a project, what makes you happier is:
That the project has good results
Being sincerely praised by your colleagues

# Which of these attitudes toward goals describes you best?
Once I set a goal, I will do my best to accomplish it
I normally can't achieve my goals and keep changing them

# When a friend talks to you about a problem and wants advice, you tend to:
Think from your friend's point of view
Think from an objective point of view

# The mistakes you are more likely to make are:
Overthinking and missing opportunities
Being too reckless and damaging or losing things

# Suppose you have three months to participate in the "Activities Training Camp", which includes musical instruments, sports, and more. Would you rather:
Train multiple activities
Choose one activity and try to excel

# What would you do with work tasks that you already know very well?
Complete them on schedule
Complete them using new ideas or look for something more fun at work

# What is the most exciting and satisfying moment when implementing a plan of yours?
The first day of the plan
The last day of the plan
My plans often don't go well

# When you have to do a task, you often:
Complete it as soon as possible
Set goals and complete them step by step
Complete it at the last moment before the deadline

# In a parallel universe, you would rather be a/an:
Politician
Artist
Business magnate
Inventor

# Which article are you more likely to read based on the headline content alone?
“These 7 microexpressions show that the other person is lying!”
“What is the principle of the heart beating?”
“Detailed explanation of the Heimlich maneuver that can save lives at critical moments”
“Experimental principle—Schrödinger's Cat”